name = "MPSKitAdapters"
uuid = "b5e06e08-62aa-43f0-8b15-6fe7988891e8"
version = "0.1.0"
authors = ["Andreas Feuerpfeil <development@manybodylab.com> and Lukas Devos"]

[deps]
BlockTensorKit = "5f87ffc2-9cf1-4a46-8172-465d160bd8cd"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorKitAdapters = "365c3f09-11dd-4b21-ae3b-5ed73578a59c"

[weakdeps]
ITensorIMPS = "b6633aba-3a78-4a21-8473-2785f157d1a4"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"

[extensions]
ITensorIMPSExt = ["ITensorIMPS", "ITensors", "MPSKit"]
ITensorMPSExt = ["ITensorMPS", "ITensors", "MPSKit"]

[compat]
BlockTensorKit = "0.3.1"
ITensorIMPS = "0.1.0"
ITensorMPS = "0.3.25"
ITensors = "0.9.15"
MPSKit = "0.13.8"
TensorKit = "0.15.3"
TensorKitAdapters = "0.1.0"
julia = "1.10"

[extras]
ITensorIMPS = "b6633aba-3a78-4a21-8473-2785f157d1a4"
