[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MPSKitAdapters = "b5e06e08-62aa-43f0-8b15-6fe7988891e8"

[compat]
Documenter = "1"
Literate = "2"
MPSKitAdapters = "0.1"